version: 2
jobs:
  unit-test:
    parallelism: 1
    working_directory: ~/nomad-migrators
    docker:
      - image: omnyway/vulcan:latest
      - image: postgres:9.6.2
    environment:
      - SERVICE_NAME: nomad-migrators
      - PG_OPTS: "-U postgres -h localhost -p 5432"
      - PGPASSWD: postgres
    steps:
      - checkout
      - run: for i in `seq 120`; do nc -v -w 1 localhost 5432 && break ; sleep 1; done
      - run: sleep 10
      - run: createdb ${PG_OPTS} nomad-test
      - run: vulcan test -s unit
  release:
    parallelism: 1
    working_directory: ~/nomad-migrators
    docker:
      - image: omnyway/vulcan:latest
    environment:
      - VERSION_FILE: ../VERSION
      - SERVICE_NAME: nomad-migrators
      - GOROOT: ""
      - GOPATH: "/root/.go"
    steps:
      - checkout
      - run: vulcan next-tag > $VERSION_FILE
workflows:
  version: 2
  build_test_release:
    jobs:
      - unit-test
      - release:
          requires:
            - unit-test
          filters:
            branches:
              only: master
